import time
import random
print(" hello user, my name is Alex ! i was made by Nour yahyaoui !")
time.sleep(2)
print("my job is helping you on some parts of the web development ")
time.sleep(1)
print("I'M  working with Nour to add more options for you but now you can select the code and copie it !")
time.sleep(1)
print("----------------------------------------------------------------")
print("")
name=input("first, can I know what is your Name :")
time.sleep(1)
print("welcome "+ name +", what do you want from me to generate to you ? ")
print("1/ JavaScript copie code that Nour used on the csspage . ")
print("2/ animations generator with options .")
print("3/ want some ready css codes ?")
time.sleep(2)
c=int(input("Enter your choice 1, 2 or 3 :"))
if c==1 :
    m=int(input("how much of scripts you want to generate, you have 1-2-3..... buttons you want to make the code for them ? :"))
    print("ok i will generate for you "+ name +" !")
    for i in range(m):
        time.sleep(1)
        print("")
        print("const btn"+str(i+1) +"=document.getElementById(" + "'" + "button"+str(i+1)+"');")
        print("const text"+str(i+1) +"=document.querySelector(" + "'." + "p"+str(i+1)+"');")
        print("btn"+str(i+1)+".addEventListener('click', function() {")
        print("const text =text"+str(i+1)+".textContent;")
        print("    const text =text"+str(i+1)+".textContent;")
        print("    navigator.clipboard.writeText(text);")
        print("    alert('code copied sccessfully');")
        print("});")
        print("")
    print("-----------------------------------------------------------------")
    print("")
    time.sleep(2)
    print("dont forget to give the buttons theyr ids like you see on the code and put the class of what you wnt to copie !")
    print("")
    time.sleep(1)
    print("happy coding " + name + " !")
    print("")
    print("------------------------------------------------------------")
elif c==2 :
    print("1/ animation of background color change with your choice of how much parts in the animation 100% randomly .")
    time.sleep(0.5)
    print("")
    print("2/ animation of background color change and transform scale change 1-1.1 with your choice of how much parts in the animation .")
    time.sleep(0.5)
    print("")
    print("3/ animation of background/transform/rotate change with your choice of how much parts in the animation .")
    time.sleep(0.5)
    print("")
    print("4/ animation of border radius change randomly with your choice of how much parts in the animation")
    time.sleep(0.5)
    print("")
    print("5/ animation of border radius/border color change randomly with your choice of how much parts in the animation")
    time.sleep(0.5)
    print("")
    print("6/ animation of border color change randomly with your choice of how much parts in the animation")
    time.sleep(0.5)
    print("")
    print("7/ animation of background color and border with the same color change with your choice of how much parts in the animation")
    time.sleep(0.5)
    print("")
    print("8/ animation of background color / border raduis change with your choice of how much parts in the animation")
    time.sleep(0.5)
    print("")
    print("9/ animation of background color / box shadow  with the same color change with your choice of how much parts in the animation")
    time.sleep(0.5)
    ch=int(input("what is your choice " +name+" :"))
    if ch==1:
        aniname=input("what i should call the animation "+ name+ " :")
        n=int(input("how many parts the animation should take (100-50-25-2...):"))
        print("@keyframes " + aniname +" {  ")
        for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding " + name + " !")
        print("")
        print("------------------------------------------------------------")
    elif ch==2:
        s=1
        aniname=input("what i should call the animation "+ name+ " :")
        n=int(input("how many parts the animation should take (100-50-25-2...):"))
        print("@keyframes " + aniname +" {  ")
        for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
            if s==1:
                print("transform:scale(1.1);")
                s=0
            else :
                 print("transform:scale(1);")
                 s=1
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding " + name + " !")
        print("")
        print("------------------------------------------------------------")
    elif ch==3:
         s=1
         aniname=input("what i should call the animation "+ name+ " :")
         n=int(input("how many parts the animation should take (100-50-25-2...):"))
         print("@keyframes " + aniname +" {  ")
         for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
            if s==1:
                print("transform:scale(1.1);")
                print("rotate:30deg;")
                s=0
            else :
                 print("transform:scale(1);")
                 print("rotate:-30deg;")
                 s=1
            print(" } ")
            print("} ")
            print("------------------------------------------------------------")
            print("")
            print("happy coding " + name + " !")
            print("")
            print("------------------------------------------------------------")
    elif ch==4:
         aniname=input("what i should call the animation "+ name+ " :")
         n=int(input("how many parts the animation should take (100-50-25-2...):"))
         print("@keyframes " + aniname +" {  ")
         for i in range(0,100, int(100//n)):
            n1 = random.randint(0,140)
            n2 = random.randint(0,140)
            n3 = random.randint(0,140)
            n4 = random.randint(0,140)
            print (str(i) + "% {")
            print("border-radius: "+str(n1)+"px "+str(n2)+"px "+str(n3)+ " px"+ str(n4) +"px ;")
         print(" } ")
         print("} ")
         print("------------------------------------------------------------")
         print("")
         print("happy coding " + name + " !")
         print("")
         print("------------------------------------------------------------")
    elif ch==5:
        aniname=input("what i should call the animation "+ name+ " :")
        n=int(input("how many parts the animation should take (100-50-25-2...):"))
        print("@keyframes " + aniname +" {  ")
        for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("border-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
            n1 = random.randint(0,140)
            n2 = random.randint(0,140)
            n3 = random.randint(0,140)
            n4 = random.randint(0,140)
            print("border-radius: "+str(n1)+"px "+str(n2)+"px "+str(n3)+ " px)"+ str(n4) +"px ;")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding " + name + " !")
        print("")
        print("------------------------------------------------------------")
    elif ch==6:
        aniname=input("what i should call the animation "+ name+ " :")
        n=int(input("how many parts the animation should take (100-50-25-2...):"))
        print("@keyframes " + aniname +" {  ")
        for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("border-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding "+ + name + " !")
        print("")
        print("------------------------------------------------------------")
    elif ch==7:
        aniname=input("what i should call the animation "+ name+ " :")
        n=int(input("how many parts the animation should take (100-50-25-2...):"))
        print("@keyframes " + aniname +" {  ")
        for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("border-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding "+ + name + " !")
        print("")
        print("------------------------------------------------------------")
    elif ch==8:
        aniname=input("what i should call the animation "+ name+ " :")
        n=int(input("how many parts the animation should take (100-50-25-2...):"))
        print("@keyframes " + aniname +" {  ")
        for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
            n1 = random.randint(0,140)
            n2 = random.randint(0,140)
            n3 = random.randint(0,140)
            n4 = random.randint(0,140)
            print("border-radius: "+str(n1)+"px "+str(n2)+"px "+str(n3)+ " px"+ str(n4) +"px ;")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding "+ name + " !")
        print("")
        print("------------------------------------------------------------")
    elif ch==9:
         aniname=input("what i should call the animation "+ name+ " :")
         n=int(input("how many parts the animation should take (100-50-25-2...):"))
         print("@keyframes " + aniname +" {  ")
         for i in range(0,100, int(100//n)):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
            print("box-shadow: rgb("+str(n1)+","+str(n2)+","+str(n3)+") 2px 2px 20px ;")
            print(" } ")
            print("} ")
            print("------------------------------------------------------------")
            print("")
            print("happy coding "+ + name + " !")
            print("")
            print("------------------------------------------------------------")
        
    else :
        print("your choice is not found, sorry " + name +" .")
        print("click f5 to try again !") 
elif c==3:
    time.sleep(2)
    print("---------------------------------------------")
    print("")
    print("this is a small version of the website that Nour created and you can always find it on :")
    print("http://blazaartn.github.io/nour/DWU.html")
    print("")
    print("---------------------------------------------")
    time.sleep(2)
    print("1/ css simple triangle-background-change-color code .")
    print("")
    time.sleep(0.5)
    print("2/ css simple left-arrow-background-change-color code .")
    print("")
    time.sleep(0.5)
    print("3/ css simple right-arrow-background-change-color code .")
    print("")
    time.sleep(0.5)
    print("4/ css simple star-background-change-color code .")
    print("")
    time.sleep(0.5)
    print("")
    g=int(input("Enter your choice "+ name +" :"))
    if   g==1:
        print("")
        print(".class { ")
        print("width: 250px;")
        print("height: 250px;")
        print("clip*path: polygon(50% 0%, 0% 100%, 100% 100%);")
        print("animation: change 30s infinite linear alternate;")
        print("}")
        print("@keyframes change {  ")
        for i in range(0,100,):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding " + name + " !")
        print("")
        print("------------------------------------------------------------")
        

    elif g==2:
        print("")
        print(".class { ")
        print("width: 250px;")
        print("height: 250px;")
        print("clip-path: polygon(40% 0%, 40% 20%, 100% 20%, 100% 80%, 40% 80%, 40% 100%, 0% 50%);")
        print("animation: change 30s infinite linear alternate;")
        print("}")
        print("@keyframes change {  ")
        for i in range(0,100,):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding "+ name + " !")
        print("")
        print("------------------------------------------------------------")
        
    elif g==3:
        print("")
        print(".class { ")
        print("width: 250px;")
        print("height: 250px;")
        print("clip-path: polygon(0% 20%, 60% 20%, 60% 0%, 100% 50%, 60% 100%, 60% 80%, 0% 80%);")
        print("animation: change 30s infinite linear alternate;")
        print("}")
        print("@keyframes change {  ")
        for i in range(0,100,):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding " + name + " !")
        print("")
        print("------------------------------------------------------------")
        
    elif g==4:
        print("")
        print(".class2 { ")
        print("width: 250px;")
        print("height: 250px;")
        print("    clip-path: polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);") 
        print("animation: change 30s infinite linear alternate;")
        print("}")
        
        print("@keyframes change {  ")
        for i in range(0,100,):
            n1 = random.randint(0,255)
            n2 = random.randint(0,255)
            n3 = random.randint(0,255)
            print (str(i) + "% {")
            print("background-color:rgb("+str(n1)+","+str(n2)+","+str(n3)+");")
        print(" } ")
        print("} ")
        print("------------------------------------------------------------")
        print("")
        print("happy coding "+ name + " !")
        print("")
        print("------------------------------------------------------------")
        
    else:
        print("your choice is invalid !")
else :
    print("your choice is not found, sorry " + name +" .")
    print("click f5 to try again !") 
    
print("-------------------------------------------------------------------thanks for using me !")
